### ISSUE TITLE
storeInUserPreferences question?

### ISSUE THREAD

**Issue by nikolakurtic** [christian-schlichtherle/truelicense#9]
Is storeInUserPreferences mandatory? Is there a way to omit storing license?
Thanks!

**Comment by nikolakurtic** [comment]
Ok, I just tested manager.uninstall() and it removes license from Preferences.

**Comment by christian-schlichtherle** [comment]
> Is storeInUserPreferences mandatory? Is there a way to omit storing license?
> Thanks!

It's not mandatory. Your can...

+ call `.storeInSystemPreferences(Class<?> clazz)` instead, although it's not recommended because on some OS the user would need administrative privileges to do that.
+ call `.storeIn(Store store)` where the `Store` parameter could be `BIOS.memory()` if you really don't want to persist the license key.
+ call `manager.uninstall()` as you've figured.

I wonder what the use case is, however. Do you want to preview the license key? Then you should go with `.storeIn(BIOS.memory())` as explained above. Otherwise, the call to `manager.install(...)` does exactly what it's name suggests: It installs the license key in the configured store.
